OUT-479 Task card overflow issue
copilot-platforms/tasks-app pull request #109
Opened 2024-06-28 09:40 UTC by arpandhakal

- also introduced divider in CU view

### Tasks

- [Task card overflow issue](https://linear.app/copilotplatforms/issue/OUT-479/task-card-overflow-issue)

### Changes

- [x] Fixed task card overflow in board view by truncating text which are more than 22 char for assignee Name.
- [x] Introduces divider in CU task view with 1px padding and color aligning to figma design.

### Testing Criteria

![image](https://github.com/copilot-platforms/tasks-app/assets/46821825/47d74281-9d2e-4f39-8f9d-4d98639e7b00)

2024-07-01 12:42 UTC, aatbip requested changes

2024-07-01 12:42 UTC, aatbip commented on src/components/cards/TaskCard.tsx
> +                )}
I think this computation is unnecessary overload to the app. I think it is better to create an `hoc` that supports trucating with the styling below. We can achieve this using simple css styling - 
```css
width: 146px; //the size of visible element
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

2024-07-01 12:42 UTC, aatbip commented on src/components/cards/ClientTaskCard.tsx
> +                    )}
I think we are doing two things for the same purpose here. We are giving the above styling in `sx` prop which is exactly responsible for the truncate styling. We don't need to use `truncateText` function in this case.

2024-07-01 12:42 UTC, aatbip commented on src/types/constants.ts
> +  TASK_CARD_NAME = 22,
I think all of these can be removed and simply use the css styling for truncation. We can create an `hoc` for re-usability. 

I think using such numbers for truncation will bring inconsistency and won't be usable in all kinds of design. It's better to let CSS handle such things for various screen sizes. Styling related jobs should be given to CSS as much as possible for easy life.

2024-07-02 10:11 UTC, rrojan approved these changes
LGTM :trophy:

2024-07-02 10:31 UTC, rrojan approved these changes
LGTM again

2024-07-02 10:34 UTC, rrojan approved these changes

2024-07-03 05:52 UTC, aatbip approved these changes

2024-07-03 06:13 UTC, merged