OUT-606 | Selecting assignee does not work as expected
copilot-platforms/tasks-app pull request #182
Opened 2024-07-22 16:55 UTC by rrojan

### Tasks

- [OUT-606 | Selecting assignee does not work as expected](https://linear.app/copilotplatforms/issue/OUT-606/selecting-assignee-does-not-work-as-expected)

### Changes

- [x] Implement filtered assignee reset when a value is selected

2024-07-23 09:58 UTC, aatbip requested changes
Below are some of the comments regarding the revalidation. 
I am also getting another major concerning issue here which was mentioned in another PR as well. If I create a new user from the dashboard, then I can search for that user in the assignee selector but when a task is created, I see "No assignee" instead of the selected assignee. Please see below loom demonstration - 

[LOOM](https://www.loom.com/share/792537fe15bb4b538f4d87fca05d8ab1?sid=a755cc88-233c-451a-88de-8125e521007f)

2024-07-23 09:58 UTC, aatbip commented on src/app/client/page.tsx
>    })
This revalidation will be overridden by `export const fetchCache = 'force-no-store'` so it can be removed.

2024-07-23 09:58 UTC, aatbip commented on src/app/detail/[task_id]/[user_type]/page.tsx
> +      next: { tags: ['getAssigneeList'], revalidate: ASSIGNEE_REVALIDATION_INTERVAL },
same on this as above

2024-07-23 09:58 UTC, aatbip commented on src/app/page.tsx
> +    next: { tags: ['getAssigneeList'], revalidate: ASSIGNEE_REVALIDATION_INTERVAL },
ISR is not implementable here because rest of the fetch calls are configured to opt out of caching.

2024-07-24 11:17 UTC, rrojan commented
@aatbip this issue has been fixed in OUT-576

2024-07-24 14:56 UTC, aatbip approved these changes
lgtm

2024-07-25 11:58 UTC, arpandhakal approved these changes
LGTM

2024-07-25 12:05 UTC, merged