OUT-667 Task assigned to company says “No assignee” on client-side
copilot-platforms/tasks-app pull request #197
Opened 2024-07-29 11:28 UTC by aatbip

### Changes

- [x] ...

2024-07-30 13:23 UTC, rrojan requested changes
I think it would be best if we looked over these changes synchronously :bow:  @aatbip

2024-07-31 10:21 UTC, aatbip commented on src/app/api/tasks/tasks.service.ts
>        throw new APIError(httpStatus.UNAUTHORIZED, 'You are not authorized to perform this action')
This was just done during debugging and wasn't changed back because they both are same thing.

2024-07-31 10:59 UTC, rrojan approved these changes
LGTM :trophy:

2024-07-31 10:59 UTC, rrojan commented on src/app/client/ui/ClientTaskBoard.tsx
> +    })
```suggestion
    return tasks.filter((task) => [tokenPayload?.clientId, task.assigneeId].includes(task.assigneeId))
```

2024-07-31 11:15 UTC, merged