OUT-648 | Filter drop-down shows companies even if companies are disabled
copilot-platforms/tasks-app pull request #207
Opened 2024-07-30 12:40 UTC by rrojan

### Tasks

- [OUT-648 | Filter drop-down shows companies even if companies are disabled](https://linear.app/copilotplatforms/issue/OUT-648/filter-drop-down-shows-companies-even-if-companies-are-disabled)

### Changes

- [x] Filter out companies from backend if `Enable companies` has been turned off from workspace settings.

### Testing Criteria

- [x] [LOOM](https://www.loom.com/share/dae18f2e33b04eb39de8cc010ed1933c?sid=ec8567af-26d7-4e4c-b927-d3da82ae582e)

### Notes

- While testing this, please make sure to remember to turn *off* Enable companies from dashboard settings. Also remember to toggle it back on after testing.

2024-08-02 09:03 UTC, aatbip reviewed
lgtm. waiting for QA test before approval.

2024-08-05 13:55 UTC, Chaewang12 approved these changes
Verified

2024-08-06 09:35 UTC, aatbip requested changes
I think this changes should also be made for the `getClient` method of this class. It is used for the CU routes.

2024-08-06 13:26 UTC, aatbip approved these changes

2024-08-06 16:39 UTC, merged