OUT-692, OUT-693, OUT-694 Reduce spacing between assignees in drop-down on mobile experience
copilot-platforms/tasks-app pull request #225
Opened 2024-08-08 09:12 UTC by arpandhakal

### Tasks

- [Reduce spacing between assignees in drop-down on mobile experience](https://linear.app/copilotplatforms/issue/OUT-692/reduce-spacing-between-assignees-in-drop-down-on-mobile-experience)
- [First assignee is always shown as selected in Assignee drop-down](https://linear.app/copilotplatforms/issue/OUT-693/first-assignee-is-always-shown-as-selected-in-assignee-drop-down)
- [Search text does not reset to default state when switching between tabs](https://linear.app/copilotplatforms/issue/OUT-694/search-text-does-not-reset-to-default-state-when-switching-between)

### Changes

- [x] overwritten mui's css to apply own custom css and removed autohighlight prop from autocomplete
- [x] added global mui theme for autocompletes throughtout the application to align with figma design
- [x] added clear value function in onBlur prop of the selector's autocomplete's textfield component  

### Testing Criteria

- [LOOM](https://www.loom.com/share/02a6db3045684b8d84d12715b16e7905)

2024-08-08 09:38 UTC, rrojan requested changes
Some minor improvement, which aren't necessary directly related to PR tasks:

 
![image](https://github.com/user-attachments/assets/1d79d205-29bf-49f4-aac5-c7b49116f944)
In figma, the gap between assignee avatar and "Filter by" is 8px not 4.

![image](https://github.com/user-attachments/assets/d751cb6b-a5d8-4ba9-80c7-6b115143d880)

In figma, only the square "Close" div is highlighted when hovering on close icon, but in our implementation, the whole selector is highlighted, which could lead to a confusing user experience

2024-08-09 09:30 UTC, aatbip requested changes

2024-08-09 09:30 UTC, aatbip commented on src/theme/theme.ts
>  })
I think it's not a good idea to override the autocomplete style from the theme. We should be able to do this using css selectors.

2024-08-09 10:55 UTC, aatbip approved these changes
lgtm

2024-08-09 13:32 UTC, rrojan approved these changes
Looks good, LGTM :trophy:

2024-08-12 03:26 UTC, merged