OUT-715 Unnecessary scrollbar is shown on task details page when task title is long
copilot-platforms/tasks-app pull request #267
Opened 2024-08-21 11:33 UTC by arpandhakal

### Tasks

- [Unnecessary scrollbar is shown on task details page when task title is long](https://linear.app/copilotplatforms/issue/OUT-715/unnecessary-scrollbar-is-shown-on-task-details-page-when-task-title-is)

### Changes

- [ ] ...

2024-08-23 03:54 UTC, priosshrsth commented on src/app/globals.css
> +  height: calc(100vh - 50vh);
Can't it be just 50vh instead of using calc?

2024-08-27 07:41 UTC, rrojan requested changes
I can still reproduce this issue on tablet devices. It seems like a horizontal scrollbar appears for them as well. 

https://www.loom.com/share/6f25d50af81f4408a0a2844babfee263

2024-08-29 10:07 UTC, rrojan approved these changes
LGTM :trophy:

2024-08-29 10:09 UTC, aatbip requested changes

2024-08-29 10:09 UTC, aatbip commented on src/app/detail/ui/Sidebar.tsx
The initial assumption for the medium screen width is 600px which was also shared in this issue and was decided accordingly - https://linear.app/copilotplatforms/issue/OUT-1/create-tokens

Changing this to 700px over here is going to change the overall responsive idea of the entire app.

2024-08-29 10:19 UTC, aatbip requested changes

2024-08-29 10:19 UTC, aatbip commented on src/app/detail/ui/ToggleController.tsx
> +  const nonMobile = useMediaQuery('(min-width:700px)')
700px assumption is out of sync with the rest of the Copilot app implementation.

2024-08-29 10:19 UTC, aatbip commented on src/app/detail/ui/Sidebar.tsx
> +        width: matches ? '100vw' : { sm: '16vw', md: '20vw' },
I don't think we need to give varying height to solve this issue. Why don't we calculate the height of the title input box, and then calculate the height of the tapwrite description with respect to the height of the title input box? This makes the solution straightforward IMO.

2024-08-29 10:58 UTC, aatbip requested changes

2024-08-29 10:58 UTC, aatbip commented on src/app/detail/ui/Sidebar.tsx
> +        width: matches && showSidebar ? '100vw' : { sm: '16vw', md: '20vw' },
I think the width of the sidebar doesn't match the Figma design. According to the design, the sidebar occupied 29.5% of the total screen width which is equivalent to 366px, whereas in this PR the width of sidebar is very small i.e. ~ 336px.

2024-08-29 10:58 UTC, aatbip commented on src/app/detail/ui/ToggleController.tsx
> +  const nonMobile = useMediaQuery('(min-width:700px)')
https://github.com/copilot-platforms/tasks-app/pull/267#discussion_r1735935876

2024-08-30 11:55 UTC, aatbip requested changes
For the screen sizes below 600px, we are getting an empty space in the bottom. 

![Screenshot from 2024-08-30 17-39-35](https://github.com/user-attachments/assets/f999937a-9737-4a72-b977-2a0a12baaa6a)

2024-08-30 11:55 UTC, aatbip commented on src/app/detail/ui/Sidebar.tsx
>        }}
I think its better to use `calc` function here. Otherwise, `vw` should be nice.

2024-09-02 12:29 UTC, closed without merging