OUT-819 Support for deleting images from bucket
copilot-platforms/tasks-app pull request #296
Opened 2024-09-12 11:23 UTC by arpandhakal

### Tasks

- [Support for deleting images from bucket](https://linear.app/copilotplatforms/issue/OUT-819/support-for-deleting-images-from-bucket)

### Changes

- [x] removed unused image by applying cron job. 

### Notes

- some checks are commented out to test this in preview

2024-09-17 06:31 UTC, rrojan requested changes

2024-09-17 06:31 UTC, rrojan commented on src/app/api/workers/scrap-images/scrap-images.controller.ts
> +export const RemoveScrapImages = async (request: NextRequest) => {
Functions should be camelCased. Also please wrap this with withErrorHandler for proper error logging

2024-09-17 06:31 UTC, rrojan commented on src/app/api/workers/scrap-images/scrap-images.controller.ts
> +    })
Where did this Response come from? This is not imported

2024-09-17 06:31 UTC, rrojan commented on src/app/api/workers/scrap-images/scrap-images.service.ts
> +      if (task && (task.body as string).includes(image.filePath)) {
In our schema task.body can be undefined as well. Using `includes` on undefined will crash the endpoint.

![image](https://github.com/user-attachments/assets/f18d8ec3-7223-4a8e-8008-e75b3007ac7a)

2024-09-17 08:16 UTC, rrojan requested changes

2024-09-17 08:16 UTC, rrojan commented on prisma/schema.prisma
> +  filePath    String       @unique
We are frequently querying ScrapImages table using `where filePath = ?`, and filePath is unique. I suggest we add an index to this column for faster queries

2024-09-17 08:16 UTC, rrojan commented on prisma/schema.prisma
> +  id          String       @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
If you pull the latest feature/M2 I believe the schema files should be split into separate model files

2024-09-17 09:04 UTC, rrojan requested changes

2024-09-17 09:08 UTC, rrojan commented on src/app/api/workers/scrap-images/scrap-images.service.ts
> +      await supabase.supabase.storage.from(supabaseBucket).remove([image.filePath])
Fixed

2024-09-18 13:09 UTC, priosshrsth requested changes

2024-09-18 13:09 UTC, priosshrsth commented on src/app/detail/[task_id]/[user_type]/page.tsx
> +                    }}
Let's extract this in a variable. And also 159, 160 could be simplified in a single return statement.

2024-09-18 13:09 UTC, priosshrsth commented on src/app/detail/ui/TaskEditor.tsx
> +          }}
Again, it's better to extract these are into it's own variable and pass that variable as a function rather than declaring them inline.

2024-09-18 13:14 UTC, priosshrsth commented
@arpandhakal I am not sure if TapWrite is memoized but, I think its an expensive component to re render because of all the thingg it do (I'm guessing is it the editor, right?). What I'm seeing is we are passing inline function as a props. This might be very bad approach if my uderstanding is correct because we'll be creating new anonymous function everytime the parent is re-rendered. And essentially our child component will be re rendered every time the parent is re rendered. So I think we should start extracting those inline function in it's own variable. At least the complex ones. And maybe we should even start using **useCallBack**.

2024-09-19 07:22 UTC, rrojan approved these changes
LGTM :trophy: 
As we're leaving vercel.json as-is, please be sure to remove cron-job.org's cron task after this is merged to prod

2024-09-19 11:51 UTC, merged