OUT-821 | Opening "Filter by assignee" drop-down for second time shows incorrect assignees
copilot-platforms/tasks-app pull request #311
Opened 2024-09-24 07:59 UTC by rrojan

### Tasks

- [OUT-821 | Opening "Filter by assignee" drop-down for second time shows incorrect assignees](https://linear.app/copilotplatforms/issue/OUT-821/opening-filter-by-assignee-drop-down-for-second-time-shows-incorrect)

### Changes

- [x] It seems we had some legacy code that required us to reset to initial assignee list state on selector input change. This was causing assignee list to revert to the first array after page load everytime we triggered assignee selector. This has been fixed
- [x]  Remove unused imports & Organize imports via TS lsp

### Testing Criteria

- [x] Video:
[Screencast from 2024-09-24 13-43-24.webm](https://github.com/user-attachments/assets/1f913fc1-6d17-4662-a6f4-6a366ea4ab2b)

2024-09-25 05:12 UTC, aatbip requested changes
The changes in this PR seems like have created side effects hence bringing [THIS](https://linear.app/copilotplatforms/issue/OUT-769/filter-dropdown-search-input-persists-until-i-click-somewhere-on-the) issue back again. Please consider fixing.

2024-09-26 12:09 UTC, rrojan commented
@aatbip I tested this thoroughly and the issue doesn't seem to occur. Could you please check again, or add a loom for this

2024-09-27 04:53 UTC, aatbip commented
> @aatbip I tested this thoroughly and the issue doesn't seem to occur. Could you please check again, or add a loom for this

Please see the below LOOM video which demonstrates the issue which was resolved for [THIS](https://linear.app/copilotplatforms/issue/OUT-769/filter-dropdown-search-input-persists-until-i-click-somewhere-on-the) task - 

[LOOM](https://www.loom.com/share/8f47be6f3db4444cb327171650fd441f?sid=564acfd8-336a-40ca-9e0a-980ffc132283)

@rrojan

2024-09-27 04:54 UTC, aatbip requested changes
https://github.com/copilot-platforms/tasks-app/pull/311#issuecomment-2378397410

2024-09-30 03:05 UTC, rrojan commented
@aatbip Thanks for the loom. Seems like the task you linked to is a different one - so I couldn't repro it (it's about the search text input not getting cleared out)

2024-10-02 11:27 UTC, aatbip requested changes

2024-10-02 11:27 UTC, aatbip commented on src/components/layouts/FilterBar.tsx
> +import { stopPendingFetch } from '@/utils/fetchSideEffects'
I think this is creating another issue. The previous issue was about search result persisting when dropdown is toggled again. 
Now the issue is - dropdown doesn't show any result at all when I open it from the second time onwards. Please kindly check the video below - 

https://www.loom.com/share/fe1c7b01502046ffb628068d63804537?sid=94b29072-cb37-4623-aa5e-16277edf3ec2

2024-10-04 09:01 UTC, closed without merging