Out 324
copilot-platforms/tasks-app pull request #40
Opened 2024-05-16 11:03 UTC by arpandhakal

### Tasks

- [UI & Integration - Support attachments in Tasks](https://linear.app/copilotplatforms/issue/OUT-324/ui-and-integration-support-attachments-in-tasks)

### Changes

- [x] Applied supabase upload, fetch and remove attachments from client side.
- [x] Sent the path and relevant data coming from supabase to the server side. 
- [x] Integrated attachments api in the task details UI.
- [x] Added relavant icons to the icons list required for filetype in attachments.  

### Testing Criteria

- [LOOM](https://www.loom.com/share/7c8b7e7533b545aa88989c9e9251134a)

### Notes

- Dependent on OUT-325
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

2024-05-16 11:30 UTC, rrojan requested changes

2024-05-17 11:39 UTC, arpandhakal commented on src/lib/supabase.ts
> +export const supabase = createClient(supabaseProjectUrl, supabaseAnonKey)
I think anon key meets our use case. ref : 
https://supabase.com/docs/guides/api/api-keys

2024-05-17 11:40 UTC, arpandhakal commented on src/utils/SupabaseActions.ts
> +    window.URL.revokeObjectURL(url)
URL is redirected from next router. We need to create a link for the blob url. 
ref : https://www.geeksforgeeks.org/how-to-implement-file-download-in-nextjs-using-an-api-route/

2024-05-20 04:00 UTC, aatbip approved these changes
lgtm

2024-05-21 14:36 UTC, aatbip submitted a review, later dismissed
UI part lgtm - approved

2024-05-22 15:40 UTC, rrojan approved these changes
Other than minor requested changes, LGTM :trophy:

2024-05-22 15:40 UTC, rrojan commented on src/app/api/attachments/attachments.controller.ts
> +    throw new APIError(httpStatus.BAD_REQUEST)
Might be better to use a second message param for clarity - same for above

2024-05-23 05:11 UTC, merged