OUT 408 API - Comment Schema
copilot-platforms/tasks-app pull request #65
Opened 2024-06-03 05:53 UTC by aatbip

### Tasks

- [API-Comment Schema](https://linear.app/copilotplatforms/issue/OUT-408/api-comment-schema)

### Changes

- [x] Adds comment schema

2024-06-03 08:42 UTC, rrojan requested changes

2024-06-03 10:38 UTC, aatbip commented on prisma/schema.prisma
> +  deletedAt   DateTime?
Updated in 480e6f4a38029949f5d95b4745ed501531eed016 commit

2024-06-03 10:38 UTC, aatbip commented on prisma/schema.prisma
> +  children    Comment[]    @relation("ChildComments")
Updated in 480e6f4a38029949f5d95b4745ed501531eed016 commit

2024-06-13 07:08 UTC, aatbip commented
#71 PR merge the changes of this branch into the main

2024-06-13 07:08 UTC, closed without merging